global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'healthcare-rag-api-1'
    static_configs:
      - targets: ['rag-api-1:8000']
    metrics_path: /metrics

  - job_name: 'healthcare-rag-api-2'
    static_configs:
      - targets: ['rag-api-2:8000']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics
